# Generated by Django 2.2.26 on 2022-08-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChannelDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Channel code', max_length=1000)),
                ('channel_name', models.TextField(help_text='Channel name', max_length=1000)),
            ],
            options={
                'ordering': ['channel_name'],
            },
        ),
        migrations.CreateModel(
            name='VideoLinkDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='code', max_length=1000)),
                ('artist', models.TextField(help_text='artist', max_length=1000)),
                ('album', models.TextField(help_text='album', max_length=1000)),
                ('title', models.TextField(help_text='title', max_length=1000)),
                ('category', models.TextField(help_text='category', max_length=1000)),
                ('subcategory', models.TextField(help_text='subcategory', max_length=1000)),
                ('tag', models.TextField(help_text='tag', max_length=1000)),
            ],
            options={
                'ordering': ['artist', 'album', 'title'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannelBasic',
            fields=[
                ('videochanneldatamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.VideoChannelDataModel')),
            ],
            bases=('catalog.videochanneldatamodel',),
        ),
        migrations.CreateModel(
            name='YouTubeLinkBasic',
            fields=[
                ('videolinkdatamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.VideoLinkDataModel')),
            ],
            bases=('catalog.videolinkdatamodel',),
        ),
    ]
