# Generated by Django 2.2.26 on 2022-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videochanneldatamodel',
            old_name='code',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='videolinkdatamodel',
            name='code',
        ),
        migrations.AddField(
            model_name='videolinkdatamodel',
            name='url',
            field=models.TextField(default=0, help_text='url', max_length=1000),
            preserve_default=False,
        ),
    ]
