# Generated by Django 2.2.26 on 2022-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220816_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videochanneldatamodel',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='videochanneldatamodel',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='videochanneldatamodel',
            name='url',
        ),
        migrations.AddField(
            model_name='videochanneldatamodel',
            name='album',
            field=models.TextField(default='', help_text='album', max_length=1000),
        ),
        migrations.AddField(
            model_name='videochanneldatamodel',
            name='artist',
            field=models.TextField(default='', help_text='artist', max_length=1000),
        ),
        migrations.AddField(
            model_name='videochanneldatamodel',
            name='category',
            field=models.TextField(default='', help_text='category', max_length=1000),
        ),
        migrations.AddField(
            model_name='videochanneldatamodel',
            name='subcategory',
            field=models.TextField(default='', help_text='subcategory', max_length=1000),
        ),
        migrations.AddField(
            model_name='videochanneldatamodel',
            name='tag',
            field=models.TextField(default='', help_text='tag', max_length=1000),
        ),
        migrations.AddField(
            model_name='videochanneldatamodel',
            name='title',
            field=models.TextField(default='', help_text='title', max_length=1000),
        ),
    ]
