# Generated by Django 2.2.26 on 2022-08-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220818_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochanneldatamodel',
            name='url',
            field=models.TextField(default=2, help_text='url', max_length=1000),
            preserve_default=False,
        ),
    ]
